spring:
  profiles:
    active: development-h2

aws:
  cognito:
    region: ${COGNITO_REGION}
    pool-id: ${COGNITO_POOL_ID}
    client-id: 3dd3ghbnv8v9s9ika4tpgj19t5
    access-key: ${COGNITO_ACCESS_KEY}
    secret-key: ${COGNITO_SECRET_KEY}
    jwks: https://cognito-idp.${COGNITO_REGION}.amazonaws.com/${COGNITO_POOL_ID}/.well-known/jwks.json

jwt:
  registration:
    ttl: 24
    rsa-key:
      id: registration
      modulus: ${JWK_MODULUS}
      public-exponent: ${JWK_PUBLIC_EXPONENT}  
      private-exponent: ${JWK_PRIVATE_EXPONENT}   
    
---
spring:
  profiles: development-oracl
  application:
    name: user-service
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}         #INSTEAD, CAN JUST ADD ENV VARIABLES    SPRING_DATASOURCE_URL/USERNAME/PASSWORD
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.Oracle10gDialect
  devtools:
    restart:
      enabled: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 5555
---      
spring:
  profiles: development-h2
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:test 
    username: sa 
    driver-class-name: org.h2.Driver 
  jpa:
    hibernate:
      ddl-auto: create
  show-sql: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 5555

amazonProperties:
  endpointUrl: http://rideshare-photos.s3-website-us-east-1.amazonaws.com
  accessKey: ${ACCESS}
  secretKey: ${SECRET}
  bucketName: rideshare-photos