server:
  port: 5555

spring:
  application:
    name: user-service
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka